name: Testing Docker GitHub Action
description: Testing how Docker GitHub Actions work
inputs:
  directory:
    description: Directory to create
    required: true
  files:
    description: Files to create in directory
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DIRECTORY: ${{ inputs.directory }}
  args:
    - ${{ inputs.files }}
