on: [push]

jobs:
  show_stuff:
    runs-on: ubuntu-latest
    name: Moar stuff
    steps:
      - name: Hello world action step
        id: hello
        uses: mkindahl/super-meme/docker-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Show files
        run: |
          pwd
          ls -lR
