on:
  pull_request:
    types: [opened, edited]
  issues:
    types: [opened, closed, edited, labeled]
  issue_comment:
    types: [created, edited]
  push:

jobs:
  dump-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: |
          cat <<EOT
          ${{ toJSON(github) }}
          EOT
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        if: always()
        run: echo '${{ toJSON(matrix) }}'
      - name: Safe from injection
        if: always()
        run: echo "$BODY"
        env:
          BODY: ${{ github.event.pull_request.body }}
          
  show-labels:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Show labels
        run: |
          cat <<EOT
          ${{ toJSON(github.event) }}
          EOT
          echo "----"
          cat <<EOT
          ${{ toJSON(github.event.issue) }}
          EOT
          echo "----"
          cat <<EOT
          ${{ toJSON(github.event.label) }}
          EOT
          echo "----"
          cat <<EOT
          ${{ toJSON(github.event.label.*.name) }}
          EOT

  checks:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Contains 'segfault'"
        if: >-
          contains(github.event.issue.labels.*.name, 'segfault')
    
      - run: echo "Event action is not closed"
        if: github.event.action != 'closed'
