name: Show information
on:
  issues:
  issue_comment:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  dump-variables:
    name: Dump variables
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: |
          cat <<EOT
          ${{ toJSON(github) }}
          EOT
      - name: Dump job context
        run: |
          cat <<EOT
          ${{ toJSON(job) }}
          EOT
      - name: Dump steps context
        run: |
          cat <<EOT
          ${{ toJSON(steps) }}
          EOT
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  show-labels:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Show labels
        run: |
          cat <<EOT
          ${{ toJSON(github.event) }}
          EOT
          echo "----"
          cat <<EOT
          ${{ toJSON(github.event.issue) }}
          EOT
          echo "----"
          cat <<EOT
          ${{ toJSON(github.event.label) }}
          EOT
          echo "----"
          cat <<EOT
          ${{ toJSON(github.event.label.name) }}
          EOT
