on: [issues, issue_comment, push]

jobs:
  dump-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: |
          cat <<EOT
          ${{ toJSON(github) }}
          EOT
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  show-labels:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Show labels
        run: |
          echo github.event.issue.label
          cat <<EOT
          ${{ toJSON(github.event.issue.label.*.name) }}
          EOT
          
